name: Vitest CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  TEST_PORTAL_URL: ${{ secrets.TEST_PORTAL_URL }}
  TEST_PORTAL_API_KEY: ${{ secrets.TEST_PORTAL_API_KEY }}
  CLI_BRANCH: fix/send-logic
  BUILD_NAME: ${{ github.workflow }}
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  REPOSITORY_NAME: ${{ github.repository }}
  REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ENVIRONMENT: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          repository: sv-kisel/vitest-junit
          ref: main

      - name: Show files
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'

      - name: Configure npm auth for GitHub Packages
        run: |
          echo "@vention-test-portal:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_GITHUB_TOKEN }}" >> .npmrc
   
      - name: Install test reporter CLI
        run: |
          npm install @vention-test-portal/test-portal-integration-cli

      # 4Ô∏è Run Vitest tests
      - name: Run Vitest
        run: npm run test
        continue-on-error: true

      - name: Upload Vitest report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: reports/vitest-report.json

      - name: Upload Test Results
        if: always()
        run: |
          npx @vention-test-portal/test-portal-integration-cli upload \
            --input $GITHUB_WORKSPACE/reports/vitest-report.json \
            --type vitest \
